#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &



bspc monitor -d I II III IV V

bspc config border_width          2
bspc config window_gap            6
bspc config top_padding           32

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true
bspc config focus_follows_pointer true

picom &
polybar -r 2>~/.config/polybar/log &
# ~/bin/feh-cache &
hsetroot -solid black &
# # eval `cat ~/.fehbg` &
dunst & 
# playerctld daemon &

unclutter --timeout 10 --exclude-root &
xsetroot -cursor_name left_ptr &
# blueman-applet &
# nm-applet &
setxkbmap -layout "us,ru" -option "grp:caps_toggle" &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
